Update cppcheck-full.yaml

diff --git a/.github/workflows/cppcheck-full.yaml b/.github/workflows/cppcheck-full.yaml
--- a/.github/workflows/cppcheck-full.yaml
+++ b/.github/workflows/cppcheck-full.yaml
@@ -36,13 +36,12 @@ jobs:
           cat all_files.txt
 
       - name: Run Cppcheck on all files
-        continue-on-error: true
         id: cppcheck
         run: |
           files=$(cat all_files.txt)
           if [ -n "$files" ]; then
             echo "Running Cppcheck on all files: $files"
-            cppcheck --enable=all --inconclusive --check-level=exhaustive --error-exitcode=1 --suppressions-list=.cppcheck_suppressions $files 2> cppcheck-report.txt
+            cppcheck --enable=all --inconclusive --check-level=exhaustive --error-exitcode=1 --suppressions-list=.cppcheck_suppressions $files 2> cppcheck-report.txt || true
           else
             echo "No C++ files found."
             touch cppcheck-report.txt
@@ -59,6 +58,17 @@ jobs:
           name: cppcheck-report
           path: cppcheck-report.txt
 
-      - name: Fail the job if Cppcheck failed
-        if: ${{ steps.cppcheck.outcome == 'failure' }}
+      - name: Check for Cppcheck errors
+        id: check-cppcheck-errors
+        run: |
+          if grep -q 'error' cppcheck-report.txt; then
+            echo "Cppcheck found errors."
+            echo "error=true" >> $GITHUB_ENV
+          else
+            echo "No errors found by Cppcheck."
+            echo "error=false" >> $GITHUB_ENV
+          fi
+
+      - name: Fail the job if Cppcheck found errors
+        if: env.error == 'true'
         run: exit 1
